### ISSUE TITLE
[React 15.2.1] Unknown prop `styleName`

### ISSUE THREAD

**Issue by metalshan** [gajus/react-css-modules#156] opened 2016-07-12 10:18 UTC
Unknown prop `styleName` on div tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop.

Please provide a fix

**Comment by gajus** [comment] 2016-07-12 11:48
@metalshan Please look at the existing issues and close this issue as a duplicate once you find an existing issue.

**Comment by goodbomb** [comment] 2016-07-18 19:40
I'm still seeing this while using v3.7.7

**Comment by gajus** [comment] 2016-07-18 19:48
Closed as duplicate of https://github.com/gajus/react-css-modules/issues/147.

**Closed by gajus** 2016-07-18 19:48 UTC

**Comment by goodbomb** [comment] 2016-07-18 21:42
Okay, it may be a duplicate of #147, @gajus but the issue still occurs in v3.7.7.

**Comment by goodbomb** [comment] 2016-07-18 21:45
`className={this.props.styles.foo}` and `stlyeName='foo'` both return this error.

**Comment by gajus** [comment] 2016-07-18 21:55
> Okay, it may be a duplicate of #147, @gajus but the issue still occurs in v3.7.7.

Use the original issue to add comments.
