### ISSUE TITLE
Doesn't work on server

### ISSUE THREAD

**Issue by budarin** [gajus/react-css-modules#71] opened 2015-12-28 18:02 UTC
I want to create an isomorphic app.
But babel dosnt loaded on server - so there is an error when attach styles to a components.
Is any workaround to make reac-css-modules work on server?

**Comment by gajus** [comment] 2016-03-01 10:45
Duplicate of https://github.com/gajus/react-css-modules/issues/83

**Closed by gajus** 2016-03-01 10:45 UTC
Labels: help wanted

**Comment by anaibol** [comment] 2016-03-10 23:35
:(
