### ISSUE TITLE
isIterable causes a runtime error in IE9

### ISSUE THREAD

**Issue by 0xR** [gajus/react-css-modules#121] opened 2016-04-24 10:56 UTC
I get the erorr `Symbol is undefined` on https://github.com/gajus/react-css-modules/blob/master/src/isIterable.js#L3

Does this mean I am required to polyfill Symbol myself for react-css-modules? This is not in the README and honestly I'm not sure why `react-css-modules` would need ES2015 features which require polyfills.

**Comment by gajus** [comment] 2016-04-24 11:00
Duplicate of https://github.com/gajus/react-css-modules/issues/66

**Closed by gajus** 2016-04-24 11:00 UTC
