### ISSUE TITLE
Hitting ReactElements inside a 3rd party component

### ISSUE THREAD

**Issue by mattkrick** [gajus/react-css-modules#53] opened 2015-10-27 04:09 UTC
I have a parent component which renders a component called `LeftNav` from a library (material-ui). That component takes a `ReactElement` as a prop. 

```js
class Parent extends Component {
    render() {
        return (<LeftNav header=<div styleName="header">Foo</div> />) // header style doesn't work
    }
}
```

No rule coming from the `Parent` component sticks to the `header` element because (I assume) it's scoped under that 3rd party component, which I don't have access to. Is there a way to decorate a `ReactElement`? Right now my only alternative is to inline the style: `<LeftNav header=<div style={{background: 'black'}}>Foo</div>/>`

**Comment by gajus** [comment] 2015-10-27 08:08
Duplicate of https://github.com/gajus/react-css-modules/issues/11. Refer to  https://github.com/gajus/react-css-modules#styles-property.

**Closed by gajus** 2015-10-27 08:08 UTC
Labels: question

**Comment by mattkrick** [comment] 2015-10-27 15:48
Perhaps there is a bug? The `styleName` is being picked up, mapped, and hashed, but the DOM element is left without a `class` prop. 

In my code: 
`<div styleName={this.props.styles.overview}>`

In the react tab of chrome: 
`<div styleName="foo-import__overview___3U6J0">` //so far so good

In the DOM Elements tab:
`<div data-reactid=".0.$=10:0.1.0">Overview</div>`

What I should see: 
`<div class="foo-import__overview___3U6J0" data-reactid=".0.$=10:0.1.0">Overview</div>`

**Comment by gajus** [comment] 2015-10-27 16:11
Not a bug. I have just referred you to the answer. This behaviour is by design – it is designed to prevent accidental styling of child component.

**Comment by mattkrick** [comment] 2015-10-27 16:37
Not sure I understand, comments added:

```
class extends React.Component {
    render () {
        let itemTemplate;

        //function itemTemplate takes a name and returns a ReactElement.
        //the function is never used
        itemTemplate = (name) => {
            return <li styleName={this.props.styles.foo}>{name}</li>;
        }; 
        //a List component takes an undefined variable "name". 
        //maybe name should be itemTemplate?
        //if so, I'm passing in a function & not an element, which will raise a PropType flag 
        return <List itemTemplate={name} />;
    }
}
```

**Comment by gajus** [comment] 2015-10-27 16:42
Ah, thats an error in the docs. It should have been.

```js
class extends React.Component {
    render () {
        let itemTemplate;

        itemTemplate = (name) => {
            return <li styleName={this.props.styles.foo}>{name}</li>;
        }; 
        
        return <List itemTemplate={itemTemplate} />;
    }
}
```

`itemTemplate` is used by `List` component to generate children elements.

**Comment by gajus** [comment] 2015-10-27 16:46
In your example, you are creating an element and passing that element as a property to another component:

```js
class Parent extends Component {
    render () {
        let headerElement;

        headerElement = <div styleName="header">Foo</div>;

        return <LeftNav header={headerElement} />;
    }
}
```

I am assuming, `LeftNav` is ~:

```js
class LeftNav extends Component {
    render () {
        return <div>
            {this.props.header}
        </div>;
    }
}
```

Note that it is `LeftNav` that renders the `headerElement` and you are using `react-css-modules` to decorate `Parent` component.

In this scenario, you need to explicitly set `className` using [`this.props.styles`](https://github.com/gajus/react-css-modules#styles-property), e.g.

```js
class Parent extends Component {
    render () {
        let headerElement;

        headerElement = <div className={this.props.styles.header}>Foo</div>;

        return <LeftNav header={headerElement} />;
    }
}
```

**Comment by mattkrick** [comment] 2015-10-27 16:59
Ohhhh! That does the trick, the example had me using `styleName` instead of `className`. Thanks for your help, everything works great now :+1:
