### ISSUE TITLE
How to use styleNames in loops?

### ISSUE THREAD

**Issue by andreasklinger** [gajus/react-css-modules#29] opened 2015-09-22 22:54 UTC
```js
import React from 'react';
import CSSModules from 'react-css-modules';

import styles from 'styles/components/PostCardList/index.css';

const Test = React.createClass({
  render() {
    const posts = this.props.posts.map(this.renderItem);
    return (
      <div styleName="list-test">
        {posts}
      </div>
    );
  },

  renderItem(post) {
    return (
      <div key={post.id} styleName="item">
        <PostCard
          post={post}
          trackOptions={this.props.trackOptions} />
      </div>
    );
  },
});

export default CSSModules(Test, styles);
```

The list-test styleName gets added - the item ones are not.

**Comment by gajus** [comment] 2015-10-02 11:46
Duplicate of https://github.com/gajus/react-css-modules/issues/11.

**Closed by gajus** 2015-10-02 11:46 UTC
Labels: question

**Comment by gajus** [comment] 2015-10-02 13:24
@andreasklinger Refer to https://github.com/gajus/react-css-modules#styles-property.

**Comment by gajus** [comment] 2016-01-08 16:05
See https://github.com/gajus/react-css-modules/issues/11#issuecomment-170040985.
