### ISSUE TITLE
errorWhenNotFound does not fire with misnamed styleClass assignment

### ISSUE THREAD

**Issue by bdefore** [gajus/react-css-modules#10] opened 2015-08-28 12:32 UTC
I'm not getting any webpack errors when assigning `styleName` to a nonexistent class, i.e. `<div styleName='bupkis'>`. The documentation mentions this option is true by default (and a feature I'd quite like to have) but with or without specifying `{ errorWhenNotFound: true }` in my options, it does not appear to work.

My webpack configuration, in case that may be applicable:

```
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loaders: ['react-hot', 'babel?stage=0&optional=runtime&plugins=typecheck']},
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.scss$/, loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap' },
      { test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader?limit=10000&mimetype=application/font-woff' },
      { test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader?limit=10000&mimetype=application/font-woff2' },
      { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader?limit=10000&mimetype=application/octet-stream' },
      { test: webpackIsomorphicToolsPlugin.regular_expression('images'), loader: 'url-loader?limit=10240' }
    ]
```

**Comment by gajus** [comment] 2015-08-28 13:52
Thats a bug. Default configuration had wrong value, both in the code base and in the test case... Thats what I get for using copy-paste.

Please upgrade to 3.0.2.

**Comment by bdefore** [comment] 2015-08-28 14:29
With 3.0.2 I now receive an error not found error for any class, including valid ones. It works fine if i pass false for errorWhenNotFound.

An example:
```
{"error":"Error: \"container\" CSS module is undefined.\n    at /Users/bdefore/code/react-css-modules-test/node_modules/react-css-modules/dist/linkClass.js:46:27\n    at Array.map (native)\n    at linkClass (/Users/bdefore/code/react-css-modules-test/node_modules/react-css-modules/dist/linkClass.js:41:38)\n    at _class.render (/Users/bdefore/code/react-css-modules-test/node_modules/react-css-modules/dist/index.js:51:51)\n    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/bdefore/code/react-css-modules-test/node_modules/react/lib/ReactCompositeComponent.js:789:34)\n    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/bdefore/code/react-css-modules-test/node_modules/react/lib/ReactCompositeComponent.js:816:14)\n    at [object Object].wrapper [as _renderValidatedComponent] (/Users/bdefore/code/react-css-modules-test/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/bdefore/code/react-css-modules-test/node_modules/react/lib/ReactCompositeComponent.js:237:30)\n    at [object Object].wrapper [as mountComponent] (/Users/bdefore/code/react-css-modules-test/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/Users/bdefore/code/react-css-modules-test/node_modules/react/lib/ReactReconciler.js:38:35)"}
```

**Comment by gajus** [comment] 2015-08-28 14:48
Are you certain that it throws an error if class is found? Please console.log to ensure that the key you are looking for exists.

**Comment by bdefore** [comment] 2015-08-28 14:57
If I log out styles and styleNames from within `node_modules/react-css-modules/dist/linkClass.js` on line 41, I get the following:

```
[1] styles http://localhost:3001/dist/./../../node_modules/css-loader/lib/css-base.js")();
[1] // imports
[1] exports.i(require("-!./../../node_modules/css-loader/index.js?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!./../../node_modules/autoprefixer-loader/index.js?browsers=last 2 version!./../../node_modules/sass-loader/index.js?outputStyle=expanded&sourceMap!flexboxgrid/dist/flexboxgrid.css"), undefined);
[1]
[1] // module
[1] exports.push([module.id, ".foo___2Cgzl {\n  margin: 20px;\n}\n\n.headline___1t2UQ {\n  font-weight: bold;\n  font-size: 24px;\n  padding-bottom: 20px;\n}\n\n.form-content___18tyo {\n  background-color: white;\n  padding: 30px;\n  border: 1px solid #DADADA;\n}\n\n.next-btn___IsDm0 {\n}\n", "", {"version":3,"sources":["/../../../../../autoprefixer-loader/index.js?browsers=last 2 version!/Users/bdefore/code/react-css-modules-test/node_modules/sass-loader/index.js?outputStyle=expanded&sourceMap!/Users/bdefore/code/react-css-modules-test/src/views/src/views/Onboard.scss"],"names":[],"mappings":"AAAA;EACE,aAAa;CADT;;AAIN;EACE,kBAAkB;EAClB,gBAAgB;EAChB,qBAAqB;CAHZ;;AAMX;EACE,wBAAwB;EACxB,cAAc;EACd,0BAA0B;CAHb;;AAMf;CAAW","file":"Onboard.scss","sourcesContent":[".foo {\n  margin: 20px;\n}\n\n.headline {\n  font-weight: bold;\n  font-size: 24px;\n  padding-bottom: 20px;\n}\n\n.form-content {\n  background-color: white;\n  padding: 30px;\n  border: 1px solid #DADADA;\n}\n\n.next-btn {\n  composes: end-xs from 'flexboxgrid/dist/flexboxgrid.css';\n}\n"],"sourceRoot":"webpack://"}]);
[1]
[1] // exports
[1] exports.locals = {
[1]   "foo": "foo___2Cgzl",
[1]   "headline": "headline___1t2UQ",
[1]   "form-content": "form-content___18tyo",
[1]   "next-btn": "next-btn___IsDm0 " + require("-!./../../node_modules/css-loader/index.js?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!./../../node_modules/autoprefixer-loader/index.js?browsers=last 2 version!./../../node_modules/sass-loader/index.js?outputStyle=expanded&sourceMap!flexboxgrid/dist/flexboxgrid.css").locals["end-xs"] + ""
[1] }
[1] styleNames [ 'foo' ]
[1] ROUTER ERROR:   Error: "foo" CSS module is undefined.
```
I'm also not running ExtractTextPlugin and have source maps configured (see the webpack configuration in the initial post), in case that matters.

**Comment by gajus** [comment] 2015-08-28 17:01
I am not able to reproduce this in https://github.com/gajus/react-css-modules-examples. Are you able to to isolate the example and create a repository?

**Comment by bdefore** [comment] 2015-08-29 01:41
I looked into this further tonight. From the output above I can see that what I am getting is not like what like your examples are getting from `styles` in `linkClass`. You'll get an actual object back. Mine is coming out as if the loader is stringing it out, even with mine webpack loader configuration set to the same as yours. I must have something else interfering.

I think this still might indicate that there is a bug in how you're determining if a style exists, since if I set  `{ errorWhenNotFound: false }` for options, it manages to populate the styles just fine.

**Comment by gajus** [comment] 2015-08-29 09:14
`errorWhenNotFound` does not affect how presence of a class is determined. It only affects wether an error is thrown when CSS Module is not found:

```
if (styles[styleName]) {
    return styles[styleName];
} else {
    if (options.errorWhenNotFound === true) {
        throw new Error(`"${styleName}" CSS module is undefined.`);
    }

    return '';
}
```

Just to be clear: The error about a not found CSS Module will appear in the `console.log` and will break the app, not during the build process. Is this your expectation as well?

**Comment by gajus** [comment] 2015-08-29 09:15
The former would be only possible in combination with https://github.com/gajus/react-css-modules/issues/8.

**Comment by bdefore** [comment] 2015-08-29 10:02
Yup, that's the section I've been looking at. I'm ok with it happening at run time rather than build time. But the not found error for me is reporting even when it then later (with the option flag off) is able to map the styles to the DOM correctly. I'm wondering if it could check to see if styles is a real object and if not do something different?

I believe I've isolated this down to some shenanigans my setup is pulling with webpack-isomorphic-tools (https://github.com/halt-hammerzeit/webpack-isomorphic-tools) in order to enable serverside rendering of styles. At the point when `linkClass` makes the check on `styles[styleName]` it doesn't yet have a proper object created with style name mappings it can access this way. There's some discussion in the README on webpack-isomorphic-tools on require vs import that might make these play together nicely (https://github.com/halt-hammerzeit/webpack-isomorphic-tools#require-vs-import), but I haven't investigated enough to know for certain.

**Comment by bdefore** [comment] 2015-08-29 10:04
@halt-hammerzeit maybe you could have some insight on this?

**Comment by halt-hammerzeit** [comment] 2015-08-29 10:17
@bdefore When you use ExtractTextPlugin in production then you won't get style modules (in production) because they will be extracted into a .css file, therefore the `require(style.scss)` will return an empty string (= not found).

Is this what you are talking about? the production mode?

**Comment by halt-hammerzeit** [comment] 2015-08-29 10:18
When are you getting this error?
`ROUTER ERROR:   Error: "foo" CSS module is undefined.`

In what file on what line in which run mode?

**Comment by bdefore** [comment] 2015-08-29 10:22
I don't have an example yet, sorry. But the error comes from the line above in @gajus comment: https://github.com/gajus/react-css-modules/issues/10#issuecomment-135965232

I'm running in development. The error occurs with or without ExtractTextPlugin (also, ExtractTextPlugin is not necessary to run the examples of react-css-modules).

**Comment by halt-hammerzeit** [comment] 2015-08-29 10:26
@bdefore ok, so, currently I have no idea what's happening here, so, if you write a comment describing from the beginning to the end what's going on then maybe I would get an idea.

**Comment by gajus** [comment] 2015-08-29 10:55
@bdefore a working code example, end to end, in a form of a repository (e.g. https://github.com/gajus/eslint-issue-3474) would help a lot.

**Comment by matiaslarsson** [comment] 2015-09-03 16:08
@gajus @halt-hammerzeit Not sure if you still need a code example but I have the same problem as @bdefore when using 3.0.4, either using the webpack-dev-server or using a static build.

My valid css class `.schedule` is returning `Uncaught Error: "schedule" CSS module is undefined.` . It seems the following code breaks at line 34 in linkClass.js, ` if (styles[styleName]) {` since `styles` is an empty object. 

```
import React from 'react'
import CSSModules from 'react-css-modules'
import styles from './schedule.css'

// schedule.css
//
// .schedule {
// 	background-color: blue;
// }

@CSSModules(styles)
export default class extends React.Component {
	render() {
		var	scheduleDays = [{date: "2015-09-03"},{date: "2015-09-04"}].map(day => {
			return <div>Hello: {day.date}</div>
		});

	    return <div styleName="schedule">{scheduleDays}</div>
  	}
}
```

**Comment by halt-hammerzeit** [comment] 2015-09-03 16:12
@matiaslarsson just to narrow down the possible root cause: are you using webpack-isomorphic-tools or not?

**Comment by matiaslarsson** [comment] 2015-09-03 16:17
Nope, https://github.com/HenrikJoreteg/hjs-webpack config extended with Babel Stage 0 and ExtractTextPlugin as per react-css-modules documentation.

```
config.module.loaders.forEach(function (filter) {

	// Babel Stage 0 for ES7 decorators
	if (filter.loaders) {
		filter.loaders.forEach(function(loader, idx, arr) {
			if (loader === 'babel-loader') {
				arr[idx] = 'babel-loader?stage=0'
			}
		})
	}

	// React-css-modules
	if(filter.loader === 'style-loader!css-loader!postcss-loader') {
		filter = {
			test: /\.css$/,
			loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
		}
	}
})

config.plugins.push(new ExtractTextPlugin('app.css', { allChunks: true }));
```

**Comment by matiaslarsson** [comment] 2015-09-03 16:21
Also fails when i turn off Stage 0 and drop the decorator.

```
import React from 'react'
import CSSModules from 'react-css-modules'
import styles from './schedule.css'

//@CSSModules(styles)
class Test extends React.Component {
	render() {
		var	scheduleDays = [{date: "2015-09-03"},{date: "2015-09-04"}].map(day => {
			return <div>Hello: {day.date}</div>
		});

	    return <div styleName="schedule">{scheduleDays}</div>
  	}
}

export default CSSModules(Test, styles);

```

**Comment by gajus** [comment] 2015-09-03 19:06
The only way I can assist with this issue is if someone creates a repository containing a complete set of files required to reproduce the issue.

**Comment by matiaslarsson** [comment] 2015-09-04 10:37
@gajus OK, will do that and get back to you next week!

**Comment by matiaslarsson** [comment] 2015-09-09 15:07
@gajus please see the repository https://github.com/matiaslarsson/react-css-modules-issue-10

When you run it through the dev server or build it you should see `Uncaught Error: "testStyle" CSS module is undefined.`

**Comment by gajus** [comment] 2015-09-09 15:16
@matiaslarsson Thank you for doing this.

I have done:

```sh
git clone https://github.com/matiaslarsson/react-css-modules-issue-10.git
cd react-css-modules-issue-10/
npm install
webpack-dev-server
```

and it works as expected:

<img width="903" alt="screen shot 2015-09-09 at 16 16 12" src="https://cloud.githubusercontent.com/assets/973543/9765850/216de6d4-570e-11e5-8db6-5b01d849d3b1.png">

**Comment by matiaslarsson** [comment] 2015-09-09 15:26
@gajus Great! I hope you can find out what's wrong!

**Comment by gajus** [comment] 2015-09-09 15:48
@matiaslarsson Sorry, I didn't look at the code. This thread is for a different issue, though.

Regarding your case. You have an error in your webpack.config.js:

```js
if (filter.loader === 'style-loader!css-loader!postcss-loader') {
	filter = {
		test: /\.css$/,
		loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=NNNNNNNN__[name]__[local]___[hash:base64:5]')
	}
}
```

This does nothing. What you want is:

```js
if (filter.loader === 'style-loader!css-loader!postcss-loader') {
	filter.loader = ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
}
```

Though, you don't even need that. You can use `hjs-webpack` config as it is. Though, then you will need to prefix your CSS modules with `local:` prefix.

```css
:local .testStyle {
	background-color: red;
}
```

The latter is documented in the [CSS Modules README.md](https://github.com/css-modules/css-modules#exceptions).

**Comment by gajus** [comment] 2015-09-09 15:49
@bdefore Do you have a moment to create a repository that I could use to reproduce the issue?

**Comment by matiaslarsson** [comment] 2015-09-10 10:38
Thanks!

**Comment by gajus** [comment] 2015-09-17 12:54
Closing as it was not replicated or reported again.

**Closed by gajus** 2015-09-17 12:54 UTC
Labels: bug
