### ISSUE TITLE
Higher order component problem? props.children not present

### ISSUE THREAD

**Issue by dbashford** [gajus/react-css-modules#28] opened 2015-09-22 18:28 UTC
I'm using react-css-modules and redux.  If I `@connect` a Component first, `@CSSModules` has no effect because the [`props.children`](https://github.com/gajus/react-css-modules/blob/master/src/linkClass.js#L59) this module depends on go missing.

Is there a technique to solve this problem with React?  Or is this just a fundamental issue with the higher order component concept?  Afraid I haven't enough experience with either to know if what I'm trying to do is possible.

**Comment by gajus** [comment] 2015-10-02 11:49
Duplicate of https://github.com/gajus/react-css-modules/issues/9.

**Closed by gajus** 2015-10-02 11:49 UTC

**Comment by gajus** [comment] 2015-10-02 11:51
The general answer is that there is no reasonable workaround. It is something that can be implemented in the future, but seeing that `react-css-modules` is the only component that I know of that extends the target components `render` method, the simple workaround is to always have `react-css-modules` as the last decorator/ wrapper.

**Comment by gajus** [comment] 2015-10-02 11:54
This is more of a problem of `@connect` for not properly exposing the inherited properties. This is going to be an issue with most higher order components. Though, the workaround is simple and covers all known use cases.

**Comment by dbashford** [comment] 2015-10-02 12:26
:+1: 

Thanks for getting back to me.  My bad for not noticing the existing issue.

The workaround being "always have `react-css-modules` as the last decorator"?  I'm good with that.  It works for now.  Long-term it present a problem if something else also needs to be last.  But like you said, not really your problem. Will cross that bridge when I'm left with no workarounds.
