### ISSUE TITLE
styleName not working when component is using this.props.childern

### ISSUE THREAD

**Issue by nsisodiya** [gajus/react-css-modules#50] opened 2015-10-19 14:05 UTC
```js
<PopupBox heading={this.state.name}>
    <button onClick={this.saveChanges.bind(this)} styleName='save-btn' type='button'>
        <Icon icon='cloud-upload' />
    </button>
</PopupBox>
```

This example is not working.

However, If I move styleName then it is working..

```js
<PopupBox styleName='save-btn'  heading={this.state.name}>
    <button onClick={this.saveChanges.bind(this)} type='button'>
        <Icon icon='cloud-upload' />
    </button>
</PopupBox>
```

this is happening because PopupBox is implemented using `this.props.children`

```js
<div>
    <div className={[this.props.className] + ""} styleName='container'>
        <div styleName='popup-Box'>
            <div styleName='popup-header'>
                <PullRight><Icon styleName='close' icon='times' onClick={this.onCrossBtnClick.bind(this)}/></PullRight>

                <h3 styleName='popup-title'>{this.props.heading}</h3>
            </div>
            <div styleName='popup-body'>
                {this.props.children}
            </div>
            <div styleName='popup-footer'>
                <button type='button' styleName='popup-close' onClick={this.onCrossBtnClick.bind(this)}>Close</button>
            </div>
        </div>
    </div>
    <div styleName='backdrop' onClick={this.onOutsidePopClick.bind(this)}></div>
</div>
```

is this a known bug ?

**Comment by gajus** [comment] 2015-10-19 14:07
It is not a bug. Refer to https://github.com/gajus/react-css-modules/blob/master/README.md#styles-property

**Comment by nsisodiya** [comment] 2015-10-19 14:09
may you tell me solution - `styleName='save-btn'` is not working.

**Comment by nsisodiya** [comment] 2015-10-19 14:17
I am getting this kind of error 
`Uncaught Error: "save-btn" CSS module is undefined.`

**Comment by nsisodiya** [comment] 2015-10-19 14:21
This is work around. Thanks - using `className={styles['save-btn']} `
```
<PopupBox heading={this.state.name}>
                             <button onClick={this.saveChanges.bind(this)} className={styles['save-btn']} type='button'>
                                <Icon icon='cloud-upload'/>
                            </button>
</PopupBox>
```

**Comment by drhayes** [comment] 2015-10-23 20:53
I'm running into this issue, too. It feels like a violation of the idea of componentization.

If I use a container component and stick an element in it that has `styleName` on it, I have to remember to change to `className={styles['formerStyleName']}`? That feels weird, because now my component doesn't work exactly like every other component any more.

My co-worker and I are building an expando-type component. If its height is too large it displays "Show More...". Here's the incomplete version:

```js
import React, { Component } from 'react';
import CSSModules from 'react-css-modules';

import styles from './showMore.css';

class ShowMore extends Component {
  render() {
    let { children } = this.props;
    return <div>{ children }</div>;
  }
};

export default CSSModules(ShowMore, styles);
```

Yet, when we use it, any elements inside of it have to be modified to not use `styleName` anymore or else the `ShowMore` has to know about their class names.

Doesn't that seem strange?

**Comment by timomeh** [comment] 2015-11-25 18:38
I really like writing `styleName="my-class"` instead of `className={styles["my-class"]}`, it's much more convenient, especially when writing nice classnames with dashes.

But not being able to nest these _CSS-Module-Components_ seems a bit weird to me – and unfortunately makes this now completely useless for me. If this behaviour will be fixed, I'll totally give this another try.

**Comment by gajus** [comment] 2015-11-25 19:02
There is nothing broken about component nesting. Read my comments in this thread explaining how to stop nesting.

**Comment by gajus** [comment] 2015-11-25 19:03
how to stop automatic inheritance*

**Comment by timomeh** [comment] 2015-11-25 19:17
I don't get why each component should adapt its behaviour just because it's wrapped inside this module – but maybe I missed the point of this module. In my opinion migrating from `className` to your `styleName` should be as painless as changing `className={styles["my-class"]}` to `styleName="my-class"` – without having to consider how components are nested.

**Comment by neverfox** [comment] 2015-11-25 20:54
@gajus Should the example your link be `itemTemplate={itemTemplate}`?

**Comment by gajus** [comment] 2015-11-26 10:22
> I don't get why each component should adapt its behaviour just because it's wrapped inside this module – but maybe I missed the point of this module. In my opinion migrating from className to your styleName should be as painless as changing className={styles["my-class"]} to styleName="my-class" – without having to consider how components are nested.

I cannot make sense of your comments.

There are no considerations for how components needs to be nested.

> In my opinion migrating from className to your styleName should be as painless as changing className={styles["my-class"]} to styleName="my-class" 

Thats what it is. The prerequisite is that every component that needs to use react-css-modules must be decorated using react-css-modules higher order component.

In the case of @nsisodiya original example:

```js
<PopupBox heading={this.state.name}>
    <button onClick={this.saveChanges.bind(this)} styleName='save-btn' type='button'>
        <Icon icon='cloud-upload' />
    </button>
</PopupBox>
```

Presumably, `PopupBox` is decorated using react-css-modules component. However, `button` and `Icon` are not. Regardless, `this.props.childern` will *never* inherit their parent component styles. This would break the core principle of CSS Modules – local scope. If `this.props.children` were to inherit behaviour and CSS styles of the parent component, this would be no different from using global CSS.

**Closed by gajus** 2015-11-26 10:22 UTC

**Comment by timomeh** [comment] 2015-11-26 11:00
No, it's *not* what it is. Consider this easy example:

```
<Row>
  <Col>...</Col>
  <Col>...</Col>
</Row>
```

`Row` and `Col` are decorated with CSSModules. They both have their own styling with CSS Modules.
`Row` is just a div with `width: 960px; margin: 0 auto` and `Col` is just a div with `width: 50%; float: left;`. 

But because `Col` is nested in `Row`, `Col` *will not* have its styles. It *will* have its styles if I change `Col` back from being decorated with CSSModules and `styleName` to a "normal" Component with `className={styles....}`.

That's exactly what @nsisodiya and @drhayes described and it completely breaks everything if you're not able to nest components.

**Comment by timomeh** [comment] 2015-11-26 11:11
It's 100% understandable that using `<MyComponent styleName="my-class" />` doesn't work out-of-the-box like this. The `styleName` would need to be passed inside of `MyComponent`, for example `<div>` – and maybe this `div` has it's own styleName, because `MyComponent` itself is using CSS Modules. Then the idea of CSS Modules will start to crumble.

**Comment by gajus** [comment] 2015-11-26 13:14
@timomeh You keep referring to the original issue, but it has nothing to do to what you are talking about. It appears that you are referring to https://github.com/gajus/react-css-modules/issues/58

**Comment by timomeh** [comment] 2015-11-26 13:24
You're right, sorry. I misunderstood the original issue. #58 seems to be my problem, too. Sorry for the inconvenience.

**Comment by sarink** [comment] 2016-02-09 17:23
I hope everyone realizes that this is an option within react-css-modules, it's the `errorWhenNotFound` option. Just set it to false on your wrapper components.

ie
```
export default CSSModules(MyComponent, componentStyles, {errorWhenNotFound: false});
```
